"""Remove username uniqueness constraint

Revision ID: 795e13166835
Revises: 0d91fa0c6681
Create Date: 2025-03-16 04:05:43.383778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '795e13166835'
down_revision = '0d91fa0c6681'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_username')
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.create_index('ix_users_username', ['username'], unique=1)

    # ### end Alembic commands ###
